Repository YunoHost/apps, pull requests merged in 2024-03, with the labels that each got.

#2037 Mark matrix-puppet-discord as obsolete
  apps.toml
Labels: opinion needed

#2190 tag ffsync as replaced-by-another-app
  apps.toml
Labels: ready to merge

#2193 readme_generator: Fix typo while linking to ALL_README.md
  tools/readme_generator/messages.pot
  tools/readme_generator/templates/README.md.j2
  tools/readme_generator/tests/README.md
Labels: tools
