Repository YunoHost/apps, pull requests merged in 2024-05, with the labels that each got.

#2101 package-not-maintained needs a rework
  antifeatures.toml
Labels: medium decision

#2341 Yarr
  apps.toml
  logos/yarr.png
Labels: catalog

#2346 Add Glance to catalog
  apps.toml
  logos/glance.png
Labels: catalog

#2174 Move garradin to graveyard
  apps.toml
  graveyard.toml
Labels: pending
