Repository YunoHost/apps, pull requests merged in 2024-10, with the labels that each got.

#2011 Add linkwarden
  apps.toml
  logos/linkwarden.png
  wishlist.toml
Labels: inactive

#2077 add khatru pyramid
  apps.toml
Labels: inactive, opinion needed

#2240 feat: add Digipad app
  apps.toml
Labels: inactive, work needed
