Repository YunoHost/apps, pull requests merged in 2024-08, with the labels that each got.

#2518 add faircamp to the catalog
  apps.toml
  wishlist.toml
Labels: catalog

#2520 add bad-security-reputation& deprecated-software antifeatures to halcyon
  apps.toml
Labels: ready to merge

#2515 Implement an app rejection list
  rejectedlist.toml
  store/app.py
  tools/webhooks/webhook.py
Labels: opinion needed

#2519 add antifeatures to netdata
  apps.toml
Labels: opinion needed

#2041 Add DownloadPageAPI to the autoupdater to download from HTML web pages
  tools/autoupdate_app_sources/autoupdate_app_sources.py
  tools/autoupdate_app_sources/requirements.txt
  tools/autoupdate_app_sources/rest_api.py
Labels: inactive, tools
