Repository YunoHost/apps, pull requests merged in 2024-04, with the labels that each got.

#2201 store: edit 'Anti-features' in 'Antifeatures'
  store/messages.pot
  store/templates/app.html
Labels: ready to merge, store

#2197 Regen readme testing branch
  tools/readme_generator/regen_readme_in_batch.py
Labels: opinion needed

#2189 antifeatures: add space after french titles
  antifeatures.toml
Labels: tools

#2223 Add MicroBin to catalog
  apps.toml
Labels: catalog

#2224 Microbin
  logos/microbin.png
Labels: catalog

#2255 Yologen : add languages buttons + disclaimer
  tools/app_generator/templates/index.html
Labels: ready to merge
